artifact_location: file:///C:/Users/adria/Documents/GitHub/lab-ml-ops/mlflow_data/0
creation_time: 1719152204443
experiment_id: '0'
last_update_time: 1719152204443
lifecycle_stage: active
name: Default
